name: Bug Report
description: Report a bug in typescript-flat-serializer
title: '[BUG]: '
labels: [bug]
assignees:
  - ynixt

body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: 'Which version of typescript-flat-serializer you use?'
      options:
        - 1.0.0
        - 0.0.9
      multiple: false
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: exception-or-error
    attributes:
      label: Error
      description: Please provide the exception or error you saw
      render: 'Text'

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a minimal code that permits the bug reproduction
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: On which OS the bug appears?
      placeholder: e.g. Windows 10, macOS 11.4, other
    validations:
      required: true

  - type: input
    id: project-type
    attributes:
      label: What is your project type?
      placeholder: e.g. NodeJs, Angular, React, other
    validations:
      required: true

  - type: input
    id: build-mode
    attributes:
      label: On which build mode the bug appears?
      placeholder: e.g. Development, Production, both

  - type: textarea
    id: other
    attributes:
      label: Anything else?
