name: Feature Request
description: Suggest a feature for typescript-flat-serializer
title: '[FEAT]: '
labels: [enhancement]
assignees:
  - ynixt

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
